---
title: "Proj_income"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(ggplot2)
library(survey)
library(dplyr)
library(ggmap)
library(maps)
library(mapdata)
library(formattable)
library(ezids)
```

```{r}
RECS2015 <- read.csv("recs2015_public_v4.csv", header=TRUE, sep=",")
```

```{r}
appcost=data.frame(RECS2015$DOLLAREL,RECS2015$DOLELSPH,RECS2015$DOLELCOL,
                RECS2015$DOLELWTH,RECS2015$DOLELRFG,RECS2015$DOLELFRZ,
                RECS2015$DOLELCOK,RECS2015$DOLELMICRO,RECS2015$DOLELCW,
                RECS2015$DOLELCDR,RECS2015$DOLELDWH,RECS2015$DOLELLGT,
                RECS2015$DOLELTVREL,RECS2015$DOLELAHUHEAT,RECS2015$DOLELAHUCOL,
                RECS2015$DOLELEVAPCOL,RECS2015$DOLELCFAN,RECS2015$DOLELDHUM,
                RECS2015$DOLELHUM,RECS2015$DOLELPLPMP,RECS2015$DOLELHTBPMP,
                RECS2015$DOLELHTBHEAT,RECS2015$DOLELNEC)
summary(appcost)
```
```{r}
Spaceheating<-mean(RECS2015$DOLELSPH)
AC<-mean(RECS2015$DOLELCOL)
Waterheating<-mean(RECS2015$DOLELWTH)
refrigerator<-mean(RECS2015$DOLELRFG)
Freezer<-mean(RECS2015$DOLELFRZ)
Cooking<-mean(RECS2015$DOLELCOK)
Microwave<-mean(RECS2015$DOLELMICRO)
Clothewasher<-mean(RECS2015$DOLELCW)
Clothedryer<-mean(RECS2015$DOLELCDR)
Dishwasher<-mean(RECS2015$DOLELDWH)
Light<-mean(RECS2015$DOLELLGT)
TV<-mean(RECS2015$DOLELTVREL)
Airhandlerheating<-mean(RECS2015$DOLELAHUHEAT)
Airhandlercooling<-mean(RECS2015$DOLELAHUCOL)
Fan<-mean(RECS2015$DOLELCFAN)

meancost=c(Spaceheating, AC, Waterheating, refrigerator, Freezer, Cooking, Microwave, Clothewasher, Clothedryer, Dishwasher, Light, TV, Fan)
a<-data.frame(name=c("Spaceheating", "AC", "Waterheating", "refrigerator", "Freezer", "Cooking", "Microwave", "Clothewasher", "Clothedryer","Dishwasher", "Light", "TV", "Fan"), val=meancost)
ggplot(data=a,aes(x=name, y=val)) + 
  geom_bar(stat="identity",fill="#f68060") +coord_flip()+
  labs(title = "Annual Electricity Cost of Different Appliances ", x = "Appliances",y = "Annual Electricity Cost")
#+scale_colour_discrete('name',lables=c("Spaceheating", "AC", "Waterheating", #"refrigerator", "Freezer", "Cooking", "Microwave", "Clothewasher", #"Clothedryer","Dishwasher", "Light", "TV"))
```


---Check the normality of electricity cost

```{r}
qqnorm(RECS2015$DOLLAREL, main="Electricity Cost ", ylab = "Cost", xlab= "")
Cost_Out<-outlierKD2(RECS2015,DOLLAREL, rm=T)
qqnorm(Cost_Out$DOLLAREL, main="Electricity Cost ", ylab = "Cost", xlab= "")
```

```{r}
Income<-as.factor(Cost_Out$MONEYPY)
UTYPE<-as.factor(Cost_Out$UATYP10)
Cost<-Cost_Out$DOLLAREL
#Comsumption<-Cost_Out$KWH
newRECS2015<-data.frame(Cost,Income,UTYPE)
str(Income)
str(UTYPE)
summary(newRECS2015)

```

---Income VS. Electricity Expenditure

```{r}
newREC2015 <- newRECS2015 %>%
  mutate(Income = as.factor(case_when(Income == 1 ~ "Less than $20,000",
                                       Income == 2 ~ "$20,000 - $39,999",
                                       Income == 3 ~ "$40,000 - $59,999",
                                       Income == 4 ~ "$60,000 to $79,999",
                                       Income == 5 ~ "$80,000 to $99,999",
                                       Income == 6 ~ "$100,000 to $119,999",
                                       Income == 7 ~ "$120,000 to $139,999",
                                       Income == 8 ~ "$140,000 or more")))

ggplot(data=newRECS2015, aes(x =Income, y=Cost, color=Income)) + 
  geom_boxplot( outlier.shape=16, outlier.size=1.5) +
  labs(title = "Annual Electricity Cost Between Different Income Level ", x = "Income level",y = "Annual Electricity Cost")+
scale_colour_discrete("Income level",labels = c("1: Less than $20,000","2: $20,000 - $39,999", "3: $40,000 - $59,999", "4: $60,000 - $79,999", "5: $80,000 - $99,999", "6: $100,000 - $119,999", "7: $120,000 - $139,999", "8: $140,000 or more" ))

```


#```{r}
#newRECS2015 %>%
#  arrange(Cost)%>%
#  mutate(Income = factor(Income, 
#                          levels = c("Less than $20,000",
#                                     "$20,000 - $39,999",
#                                     "$40,000 -$59,999",
#                                     "$60,000 - $79,999",
#                                     "$80,000 - $99,999", 
#                                     "$100,000 - $119,999", 
#                                     "$120,000 - $139,999",
#                                     "$140,000 or more")))%>%
#ggplot(aes(x =Income,y=Cost, color = Income)) + 
#  geom_boxplot(stat = "boxplot") +
#  labs(title = "Annual  Electricity Cost Between Different Income Level ", 
#       x = "Income level",
#       y = "Annual Electricity Cost")+  
#  theme(axis.text.x = element_text(angle = 45, size = 9, margin = #margin(r=0)),axis.text.y=element_blank())


#```

```{r}
df<-data.frame(Cost, Income,UTYPE)
income_aov<-aov(Cost~Income, data=df)
#income_K_aov<-aov(KWH~MONEYPY, data=RECS2015)
summary(income_aov)
#summary(income_K_aov)
```

---Urban type vs Electricity Expenditure
```{r}
ggplot(data=df, aes(x =UTYPE,y=Cost,color=UTYPE)) + 
  geom_boxplot(outlier.shape=16, outlier.size=1.5) +
  labs(title = "Annual Electricity Cost  Between Different Urban Type ", x = "Urban Type",y = "Annual Electricity Cost") + scale_colour_discrete("Urban Tpye",labels = c("C: Urban Cluster","R: Rural", "U: Urban Area" ))
```

```{r}

Urban_aov<-aov(Cost~UTYPE, data=df)
summary(Urban_aov)

```

---Rooms VS. Electricity Expenditure


```{r}
#Rooms<-Cost_Out$TOTROOMS+Cost_Out$BEDROOMS
Rooms<-as.factor(Cost_Out$TOTROOMS+Cost_Out$BEDROOMS)
meanroom<-mean(Cost_Out$TOTROOMS+Cost_Out$BEDROOMS)
ggplot(data=df, aes(x =Rooms,y=Cost,color=Rooms)) + 
  geom_boxplot(outlier.shape=16, outlier.size=1.5) +
  labs(title = "Annual Electricity Cost  of Different Numbers of Rooms ", x = "Numbers of Rooms",y = "Annual Electricity Cost")
summary(Rooms)
```


